import type { Command } from 'commander'
import { defaultIo, dim, err, type CliIo } from './ui.js'

// `looprail completion zsh|bash|fish` - prints a completion script for the
// shell, generated from the live command list so it can never drift from
// what the CLI actually ships. Static command/flag completion (the premium
// baseline); no dynamic runId completion - that would run node on every tab.

function commandEntries(program: Command): Array<{ name: string; description: string }> {
  return program.commands
    .filter((c) => !c.name().startsWith('_'))
    .map((c) => ({ name: c.name(), description: c.description().split('\n')[0].replace(/'/g, '') }))
}

export function zshCompletion(program: Command): string {
  const entries = commandEntries(program)
  const cmds = entries.map((e) => `    '${e.name}:${e.description.replace(/:/g, '-')}'`).join('\n')
  return `#compdef looprail
# looprail zsh completion - generated by \`looprail completion zsh\`
_looprail() {
  local -a commands
  commands=(
${cmds}
  )
  if (( CURRENT == 2 )); then
    _describe 'command' commands
  else
    _files
  fi
}
_looprail "$@"
`
}

export function bashCompletion(program: Command): string {
  const names = commandEntries(program).map((e) => e.name).join(' ')
  return `# looprail bash completion - generated by \`looprail completion bash\`
_looprail() {
  local cur="\${COMP_WORDS[COMP_CWORD]}"
  if [ "\$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( \$(compgen -W "${names}" -- "\$cur") )
  else
    COMPREPLY=( \$(compgen -f -- "\$cur") )
  fi
}
complete -F _looprail looprail
`
}

export function fishCompletion(program: Command): string {
  return commandEntries(program)
    .map((e) => `complete -c looprail -n '__fish_use_subcommand' -a '${e.name}' -d '${e.description.replace(/'/g, '')}'`)
    .join('\n') + '\n'
}

export function completionAction(
  shell: string | undefined, program: Command, deps: { io?: CliIo } = {},
): number {
  const io = deps.io ?? defaultIo
  if (shell === 'zsh') { io.out(zshCompletion(program)); return 0 }
  if (shell === 'bash') { io.out(bashCompletion(program)); return 0 }
  if (shell === 'fish') { io.out(fishCompletion(program)); return 0 }
  io.out(err('usage: looprail completion <zsh|bash|fish>'))
  io.out(dim('  zsh:  looprail completion zsh > ~/.zsh/completions/_looprail  (with fpath+=~/.zsh/completions)'))
  io.out(dim('  bash: looprail completion bash >> ~/.bashrc'))
  io.out(dim('  fish: looprail completion fish > ~/.config/fish/completions/looprail.fish'))
  return 1
}

export function registerCompletion(program: Command): void {
  program
    .command('completion [shell]')
    .description('print a shell completion script (zsh, bash, or fish)')
    .action((shell: string | undefined) => {
      process.exitCode = completionAction(shell, program)
    })
}
